name: Deploy GitHub Pages

on:
  repository_dispatch:
    types: ["deploy"]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout content repo
        uses: actions/checkout@v4
        with:
          repository: kumas-k/kumas-log-content
          token: ${{ secrets.GH_ACTIONS_TOKEN }}
          path: content

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
